import argparse
import json
from pathlib import Path

import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
import numpy as np


def parse_args():
    parser = argparse.ArgumentParser(
        description=(
            "Plot a paper-style non-IID client/class distribution bubble chart "
            "from split_stats.json."
        )
    )
    parser.add_argument(
        "--split-stats",
        type=Path,
        required=True,
        help="Path to split_stats.json generated by scripts/data_preprocess.py.",
    )
    parser.add_argument(
        "--output",
        type=Path,
        required=True,
        help="Output image path, e.g. results/figures/iot_noniid_split.png.",
    )
    parser.add_argument(
        "--count-field",
        choices=("train", "test", "total"),
        default="train",
        help="Which sample count to visualize in bubble size.",
    )
    parser.add_argument(
        "--title",
        type=str,
        default="Non-IID Client-Class Distribution",
        help="Figure title.",
    )
    parser.add_argument(
        "--label-mode",
        choices=("id", "name"),
        default="id",
        help="Use numeric class ids or dataset label names on the y-axis.",
    )
    parser.add_argument(
        "--style",
        choices=("default", "paper"),
        default="paper",
        help="Plot style preset. 'paper' imitates a clean IEEE-like figure style.",
    )
    return parser.parse_args()


def load_points(metadata, count_field):
    labels = metadata.get("labels", {})
    client_stats = metadata["client_stats"]

    x_vals = []
    y_vals = []
    bubble_sizes = []
    annotations = []

    all_class_ids = set()
    for client_id_str, client_info in client_stats.items():
        client_id = int(client_id_str)
        details = client_info.get("details", {})
        for class_id_str, counts in details.items():
            class_id = int(class_id_str)
            all_class_ids.add(class_id)
            if count_field == "total":
                count = int(counts.get("train", 0)) + int(counts.get("test", 0))
            else:
                count = int(counts.get(count_field, 0))
            if count <= 0:
                continue
            x_vals.append(client_id)
            y_vals.append(class_id)
            bubble_sizes.append(count)
            annotations.append(labels.get(str(class_id), str(class_id)))

    if not x_vals:
        raise ValueError("No data points found in split_stats.json for plotting.")

    return {
        "x": np.asarray(x_vals),
        "y": np.asarray(y_vals),
        "sizes": np.asarray(bubble_sizes, dtype=np.float64),
        "annotations": annotations,
        "class_ids": sorted(all_class_ids),
        "label_names": labels,
    }


def size_scale(raw_sizes):
    # Keep the minimum bubble visible while preserving count differences.
    min_count = float(np.min(raw_sizes))
    max_count = float(np.max(raw_sizes))
    if max_count == min_count:
        return np.full_like(raw_sizes, 180.0)
    normalized = (raw_sizes - min_count) / (max_count - min_count)
    return 90.0 + normalized * 520.0


def get_paper_cmap(num_classes):
    palette = [
        "#4E79A7",
        "#F28E2B",
        "#E15759",
        "#76B7B2",
        "#59A14F",
        "#EDC948",
        "#B07AA1",
        "#FF9DA7",
        "#9C755F",
        "#BAB0AC",
        "#86BCB6",
        "#D37295",
        "#8CD17D",
        "#B6992D",
        "#499894",
        "#E15759",
        "#79706E",
        "#D4A6C8",
        "#5F9ED1",
        "#C85200",
    ]
    if num_classes <= len(palette):
        return ListedColormap(palette[:num_classes])
    repeats = (num_classes + len(palette) - 1) // len(palette)
    return ListedColormap((palette * repeats)[:num_classes])


def main():
    args = parse_args()
    with args.split_stats.open("r", encoding="utf-8") as f:
        metadata = json.load(f)

    points = load_points(metadata, args.count_field)

    output_path = args.output
    output_path.parent.mkdir(parents=True, exist_ok=True)

    fig_width = max(10, metadata.get("num_clients", 10) * 0.45)
    fig_height = max(6, len(points["class_ids"]) * 0.45)
    fig, ax = plt.subplots(figsize=(fig_width, fig_height))

    if args.style == "paper":
        fig.patch.set_facecolor("white")
        ax.set_facecolor("white")
        cmap = get_paper_cmap(len(points["class_ids"]))
        alpha = 0.82
        edge_color = "#333333"
        grid_color = "#D9D9D9"
        grid_width = 0.55
        spine_color = "#222222"
    else:
        cmap = plt.get_cmap("tab20")
        alpha = 0.75
        edge_color = "black"
        grid_color = "#BDBDBD"
        grid_width = 0.5
        spine_color = "#222222"

    scatter = ax.scatter(
        points["x"],
        points["y"],
        s=size_scale(points["sizes"]),
        c=points["y"],
        cmap=cmap,
        alpha=alpha,
        edgecolors=edge_color,
        linewidths=0.6,
    )

    num_clients = int(metadata.get("num_clients", int(np.max(points["x"])) + 1))
    ax.set_xticks(np.arange(num_clients))
    ax.set_xlabel("Client ID")

    class_ids = points["class_ids"]
    ax.set_yticks(class_ids)
    if args.label_mode == "name":
        y_tick_labels = [
            points["label_names"].get(str(class_id), str(class_id)) for class_id in class_ids
        ]
    else:
        y_tick_labels = [str(class_id) for class_id in class_ids]
    ax.set_yticklabels(y_tick_labels)
    ax.set_ylabel("Class Label")

    if args.title:
        ax.set_title(args.title, fontsize=13, pad=10)
    ax.grid(True, linestyle="--", linewidth=grid_width, color=grid_color, alpha=0.8)
    ax.set_axisbelow(True)
    for spine in ax.spines.values():
        spine.set_linewidth(0.9)
        spine.set_color(spine_color)
    ax.tick_params(axis="both", labelsize=10, width=0.8, colors="#222222")

    unique_counts = sorted(set(points["sizes"].astype(int).tolist()))
    if len(unique_counts) > 4:
        legend_counts = [
            unique_counts[0],
            unique_counts[len(unique_counts) // 3],
            unique_counts[(2 * len(unique_counts)) // 3],
            unique_counts[-1],
        ]
    else:
        legend_counts = unique_counts
        legend_counts = sorted(set(int(v) for v in legend_counts))

    handles = [
        plt.scatter(
            [],
            [],
            s=size_scale(np.asarray([count]))[0],
            color="#A9A9A9",
            alpha=0.75,
            edgecolors=edge_color,
        )
        for count in legend_counts
    ]
    ax.legend(
        handles,
        [f"{count} samples" for count in legend_counts],
        title=f"{args.count_field.capitalize()} count",
        loc="upper right",
        frameon=True,
        facecolor="white",
        edgecolor="#A0A0A0",
        framealpha=0.95,
    )

    if args.style != "paper":
        cbar = fig.colorbar(scatter, ax=ax, pad=0.02)
        cbar.set_label("Class ID")

    plt.tight_layout()
    plt.savefig(output_path, dpi=300, bbox_inches="tight")
    plt.close(fig)
    print(f"Saved non-IID split plot: {output_path}")


if __name__ == "__main__":
    main()
